/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/Users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["UserRequest"];
                    "text/json": components["schemas"]["UserRequest"];
                    "application/*+json": components["schemas"]["UserRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Users/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["User"];
                        "application/json": components["schemas"]["User"];
                        "text/json": components["schemas"]["User"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Workplaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkplaceResponse"][];
                        "application/json": components["schemas"]["WorkplaceResponse"][];
                        "text/json": components["schemas"]["WorkplaceResponse"][];
                    };
                };
            };
        };
        put?: never;
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["WorkplaceRequest"];
                    "text/json": components["schemas"]["WorkplaceRequest"];
                    "application/*+json": components["schemas"]["WorkplaceRequest"];
                };
            };
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkplaceResponse"];
                        "application/json": components["schemas"]["WorkplaceResponse"];
                        "text/json": components["schemas"]["WorkplaceResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/Workplaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: number;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Success */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["WorkplaceResponse"];
                        "application/json": components["schemas"]["WorkplaceResponse"];
                        "text/json": components["schemas"]["WorkplaceResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
            workplaces?: components["schemas"]["Workplace"][] | null;
        };
        UserRequest: {
            /** Format: int32 */
            id?: number;
            name?: string | null;
        };
        Workplace: {
            /** Format: int32 */
            id?: number;
            location?: string | null;
            deadline?: string | null;
            email?: string | null;
            contactPerson?: string | null;
            notification?: string | null;
            position?: string | null;
            /** Format: int32 */
            workplaceId?: number;
            user?: components["schemas"]["User"];
        };
        WorkplaceRequest: {
            /** Format: int32 */
            id?: number;
            location?: string | null;
            deadline?: string | null;
            email?: string | null;
            contactPerson?: string | null;
            notification?: string | null;
            position?: string | null;
            /** Format: int32 */
            userId?: number;
        };
        WorkplaceResponse: {
            /** Format: int32 */
            id?: number;
            location?: string | null;
            deadline?: string | null;
            email?: string | null;
            contactPerson?: string | null;
            notification?: string | null;
            position?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
